# Homework 01-Intro of Machine Learning ZoomCamp

Link to Homework  
https://github.com/DataTalksClub/machine-learning-zoomcamp/blob/master/cohorts/2025/01-intro/homework.md 

In [1]:
import pandas as pd
import numpy as np

## Q1. Pandas version

In [2]:
pd.__version__

'2.3.2'

## Read Data File

In [3]:
df = pd.read_csv('car_fuel_efficiency.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   engine_displacement  9704 non-null   int64  
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64  
 6   origin               9704 non-null   object 
 7   fuel_type            9704 non-null   object 
 8   drivetrain           9704 non-null   object 
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 834.1+ KB


In [4]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

## Q2. Records count
How many records are in the dataset?

In [5]:
df.shape

(9704, 11)

## Q3. Fuel types
How many fuel types are presented in the dataset?

In [6]:
df['fuel_type'].unique().size

2

## Q4. Missing Values
How many columns in the dataset have missing values?

In [7]:
res = df.isna().sum()
res

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [8]:
print(f" Columns in the dataset with missing values: {res[res!=0].size}")

 Columns in the dataset with missing values: 4


## Q5. Max fuel efficiency
What's the maximum fuel efficiency of cars from Asia?

In [9]:
df[df['origin']=='Asia']['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

## Q6. Median value of horsepower

In [10]:
# Find the median value of horsepower column in the dataset.
current_median_hp = df['horsepower'].median()
current_median_hp

np.float64(149.0)

In [11]:
# Next, calculate the most frequent value of the same horsepower column.
most_frequent_value = df['horsepower'].mode()
print(f"most frequent value of horsepower column: {most_frequent_value[0]}")

most frequent value of horsepower column: 152.0


In [12]:
# Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.
df['horsepower'] = df['horsepower'].fillna(most_frequent_value[0])


In [13]:
 # Now, calculate the median value of horsepower once again.
new_median_hp = df['horsepower'].median()
new_median_hp

np.float64(152.0)

In [14]:
# Has it changed?
print(new_median_hp>current_median_hp)

True


## Q7. Sum of weights

In [15]:
# 1. Select all the cars from Asia
df_asia = df[df['origin']=='Asia']
df_asia.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                   250            1.0       174.0     2714.219310   
12                  320            5.0       145.0     2783.868974   
14                  200            6.0       160.0     3582.687368   
20                  150            3.0       197.0     2231.808142   
21                  160            4.0       133.0     2659.431451   

    acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14          14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20          18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21           NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   

    fuel_efficiency_mpg  
8             16.823554  
12            16.175820  
14            11.871091  
20            18.889083  
21            16.077730

In [16]:
# 2. Select only columns vehicle_weight and model_year
df_asian_cars_weight_year = df_asia[['vehicle_weight', 'model_year']]
df_asian_cars_weight_year

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [17]:
# 3. Select the first 7 values
df_asian_cars_weight_year = df_asian_cars_weight_year.iloc[0:7, :]
df_asian_cars_weight_year

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [18]:
# 4. Get the underlying NumPy array. Let's call it X.
X = df_asian_cars_weight_year.to_numpy()
type(X)

numpy.ndarray

In [19]:
# 5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX =  np.matmul(X.T, X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [20]:
# 6. Invert XTX.
XTX_inverse = np.linalg.inv(XTX)
XTX_inverse

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [21]:
# 7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [22]:
# 8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
t = np.matmul(XTX_inverse, X.T)
t.shape

(2, 7)

In [23]:
w = y * t
w

array([[-0.14432288, -0.11230828,  0.29810794, -0.36245398, -0.16251372,
        -0.06075771,  0.55811286],
       [ 0.28890053,  0.2560879 , -0.37871378,  0.59305003,  0.30835783,
         0.16679975, -0.72957556]])

In [24]:
# 9. What's the sum of all the elements of the result?
w.sum()

np.float64(0.5187709081074016)